---

- name: make client request
  shell: if [ ! -e /etc/openvpn/keys/{{ca_name}}/{{item.key}}.csr ] ; then . /etc/openvpn/vars && export KEY_CN={{item.key}} && openssl req -days 3650 -batch -new -keyout /etc/openvpn/keys/{{ca_name}}/{{item.key}}.key -out /etc/openvpn/keys/{{ca_name}}/{{item.key}}.csr -passout pass:"{{item.value.vpn_phrase}}" -config /etc/openvpn/openvpn-ssl.cnf; fi
  with_dict: "{{my_users}}"

- name: make client cert
  shell: if [ ! -e /etc/openvpn/keys/{{ca_name}}/{{item.key}}.crt ] ; then  . /etc/openvpn/vars && openssl ca -days 3650 -batch -out /etc/openvpn/keys/{{ca_name}}/{{item.key}}.crt -in /etc/openvpn/keys/{{ca_name}}/{{item.key}}.csr -config /etc/openvpn/openvpn-ssl.cnf ; fi
  with_dict: "{{my_users}}"
  ignore_errors: yes

- name: make openvpn dirs
  file: path={{item}} state=directory mode=755
  with_items:
    - "/etc/openvpn/clients"
    - "/etc/openvpn/clients/{{vpn_name}}"

- name: make client dir
  file: path=/etc/openvpn/clients/{{vpn_name}}/{{item.key}} state=directory mode=0700
  with_dict: "{{my_users}}"

- name: make ovpn client
  template: src=templates/ovpn.j2
            dest=/etc/openvpn/clients/{{vpn_name}}/{{item.key}}/{{item.key}}.ovpn
  with_dict: "{{my_users}}"

- name: make conf client
  template: src=templates/ovpn.j2
            dest=/etc/openvpn/clients/{{vpn_name}}/{{item.key}}/{{item.key}}.conf
  with_dict: "{{my_users}}"

- name: touch ccd
  file: path=/etc/openvpn/servers/{{vpn_name}}/ccd/{{item.key}} state=touch owner=root group=root mode=0644
  with_dict: "{{my_users}}"
