data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
    - ./sql:/sql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

app:
  restart: always
  build: ./app
  ports:
    - "80:80"
  links:
    - postgres
  #command: /usr/sbin/apache2ctl -D FOREGROUND

api:
  restart: always
  build: ./api
  ports:
    - "8000:8000"
  environment:
    DBHOST: postgres
  links:
    - postgres
  #command: bash -c "cd /usr/src/app && /usr/local/bin/gunicorn cropcompass:app -w 2 -b :8000 --reload"
