---

# stack network settings
stack_name: "HackOregon"
owner: "hackoregon"
state: "{{ lookup('env', 'PROVISION_STATE') }}"
disable_rollback: "yes"
region: "{{ lookup('env', 'AWS_REGION') }}"
keypair: "{{ lookup('env', 'KEYPAIR') }}"
mgmt_ip: "{{ lookup('env', 'MGMT_IP') }}"
vpc_base: "{{ lookup('env', 'VPC_BASE') }}"
vpc_mask: "16"
vpc_mask_long: "255.255.0.0"
subnet_mask: "20"
json_template: "roles/cloudform-launch/files/vpc_build.json"
AvailabilityZoneA: "{{ lookup('env', 'ZONEA') }}"
AvailabilityZoneB: "{{ lookup('env', 'ZONEB') }}"
AvailabilityZoneC: "{{ lookup('env', 'ZONEC') }}"


# vpn settings
vpn_name: "HackOregonVPN"
vpn_org: "HackOregon"
vpn_OU: "DevOps Division"
vpn_CN: "hackoregon.org"
vpn_city: "Portland"
vpn_state: "OR"
vpn_country: "US"
ca_name:  "HackOregonCA"
vpn_email: "bill@mcgair.com"

# security groups
security_groups:

  - sg_name: "ssh_only"
    sg_description: "default allow ssh"
    sg_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  - sg_name: "{{bastion_group}}"
    sg_description: "Bastion SG"
    sg_rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: "0.0.0.0/0"
    - proto: udp
      from_port: 1194
      to_port: 1194
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 10000
      to_port: 10000
      cidr_ip: "{{mgmt_ip}}"
    - proto: all
      from_port: -1
      to_port: -1
      cidr_ip: "{{vpc_base}}.0.0/{{vpc_mask}}"

  - sg_name: "dockerSG"
    sg_description: "default allow ssh"
    sg_rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
