---
- name: create ECS Service Scheduler IAM Role
  iam:
    iam_type: role
    name: AmazonEC2ContanerServiceRole
    state: present

- name: create ECS Container Instance IAM Role
  iam:
    iam_type: role
    name: AmazonEC2ContainerServiceforEC2Role
    state: present

- name: set ECS ServiceRole Policy
  iam_policy:
    iam_type: role
    iam_name: "ecs-instance-role"
    policy_name: "AmazonEC2ContainerServiceRolePolicy"
    policy_document: "{{playbook_dir}}/roles/aws-provision-iam/files/ContainerServicePolicy.json"
    state: present

- name: set ECS EC2 ServiceRole policy
  iam_policy:
    iam_type: role
    iam_name: "ecs-service-role"
    policy_name: "AmazonEC2ContainerServiceforEC2Policy"
    policy_document: "{{playbook_dir}}/roles/aws-provision-iam/files/ContainerServiceforEC2Policy.json"
    state: present
