---

- hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - file: path="{{playbook_dir}}/group_vars/{{region}}" state=touch
    - include_vars: "{{playbook_dir}}/group_vars/{{region}}"

    - name: create region config
      blockinfile:
        dest: "{{playbook_dir}}/group_vars/{{region}}"
        create: yes
        state: present
        block: |
          vpc_id:
          vpn_ip:
          bastion_instance:
          dmza_subnet_id:
          dmzb_subnet_id:
          dmzc_subnet_id:
          privatea_subnet_id:
          privateb_subnet_id:
          privatec_subnet_id:
      when: vpn_ip is undefined

    - name: create eip if needed
      ec2_eip:
        in_vpc: yes
        reuse_existing_ip_allowed: yes
        state: present
        region: "{{region}}"
      register: eip
      when: vpn_ip is undefined

    - name: update vpn_ip
      replace:
        dest: "{{playbook_dir}}/group_vars/{{region}}"
        regexp: "^vpn_ip:.*$"
        replace: "vpn_ip: {{eip.public_ip}}"
      when: vpn_ip is undefined

  roles:
    - cloudform-launch
