---

- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: terminating {{tag_Name_natvpn_hackoregon}} in region {{region}}
      ec2: state=absent
       instance_ids={{ec2_info.instance_ids}}
       region={{region}}

    - name: terminate 

