---

- hosts: localhost
  connection: local
  gather_facts: true

  vars:

    image_name: "aws-marketplace/amzn-ami-2015.09.f-amazon-ecs-optimized-*"
    image_owner: "679593333241"

    cluster_name: "my-ecs-cluster"
    instance_type: "t2.micro"
    instance_monitoring: "no"
    health_check_period: "300"
    health_check_type: "EC2"
    min_size: 2
    max_size: 4
    desired_capacity: 3
    replace_all_instances: "yes"

  pre_tasks:
    - include_vars: "{{playbook_dir}}/group_vars/{{region}}"

    - name: assign the elastic ip
      ec2_eip:
        in_vpc: yes
        reuse_existing_ip_allowed: yes
        state: present
        region: "{{region}}"
        device_id: "{{bastion_instance}}"
        ip: "{{vpn_ip}}"

    - name: NAT Oregon private networks
      ec2_vpc_route_table:
        region: "{{region}}"
        tags:
          Name: NAT Private networks
        vpc_id: "{{vpc_id}}"
        subnets:
          - "{{privatea_subnet_id}}"
          - "{{privateb_subnet_id}}"
          - "{{privatec_subnet_id}}"
        routes:
          - dest: 0.0.0.0/0
            instance_id: "{{bastion_instance}}"

  roles:
    - ec2-provision-ecs

  post_tasks:
   - debug: msg="Download {{region}} VPN credentials from https://{{vpn_ip}}:10000"
