---
- name: launch a cloudformations stack
  cloudformation:
    stack_name="{{stack_name}}-stack"
    state="{{state}}"
    region="{{region}}"
    disable_rollback="{{disable_rollback}}"
    template="{{json_template}}"
  args:
    template_parameters:
      KeyName: "{{keypair}}"
      SSHLocation: "{{mgmt_ip}}"
      Owner: "{{owner}}"
      VPCName: "{{stack_name}}"
      CIDR: "{{vpc_base}}.0.0/{{vpc_mask}}"
      CIDRdmzA: "{{vpc_base}}.0.0/{{subnet_mask}}"
      CIDRdmzB: "{{vpc_base}}.16.0/{{subnet_mask}}"
      CIDRdmzC: "{{vpc_base}}.32.0/{{subnet_mask}}"
      CIDRprivA: "{{vpc_base}}.112.0/{{subnet_mask}}"
      CIDRprivB: "{{vpc_base}}.128.0/{{subnet_mask}}"
      CIDRprivC: "{{vpc_base}}.144.0/{{subnet_mask}}"
  register: stack

- debug:
    msg: "Cloudform outputs: {{stack}}"

- ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{stack.stack_outputs.VPCId}}"
      "tag:Name": "dmz-A"
  register: dmza_facts

- debug:
    msg: "dmza Subnet Facts: {{dmza_facts}}"

- name: update vpc_id to "{{stack.stack_outputs.VPCId}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^vpc_id_{{region_name}}:.*$"
     replace: "vpc_id_{{region_name}}: {{stack.stack_outputs.VPCId}}"

- name: update dmza id to "{{dmza_facts.subnets.0.id}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^dmza_subnet_id_{{region_name}}:.*$"
     replace: "dmza_subnet_id_{{region_name}}: {{dmza_facts.subnets.0.id}}"

- ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{stack.stack_outputs.VPCId}}"
      "tag:Name": "dmz-B"
  register: dmzb_facts

- name: update dmzb id to "{{dmzb_facts.subnets.0.id}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^dmzb_subnet_id_{{region_name}}:.*$"
     replace: "dmzb_subnet_id_{{region_name}}: {{dmzb_facts.subnets.0.id}}"

- ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{stack.stack_outputs.VPCId}}"
      "tag:Name": "dmz-C"
  register: dmzc_facts

- name: update dmzc id to "{{dmzc_facts.subnets.0.id}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^dmzc_subnet_id_{{region_name}}:.*$"
     replace: "dmzc_subnet_id_{{region_name}}: {{dmzc_facts.subnets.0.id}}"

- ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{stack.stack_outputs.VPCId}}"
      "tag:Name": "private-A"
  register: privatea_facts

- name: update privatea id to "{{privatea_facts.subnets.0.id}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^privatea_subnet_id_{{region_name}}:.*$"
     replace: "privatea_subnet_id_{{region_name}}: {{privatea_facts.subnets.0.id}}"

- ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{stack.stack_outputs.VPCId}}"
      "tag:Name": "private-B"
  register: privateb_facts

- name: update privateb id to "{{privateb_facts.subnets.0.id}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^privateb_subnet_id_{{region_name}}:.*$"
     replace: "privateb_subnet_id_{{region_name}}: {{privateb_facts.subnets.0.id}}"

- ec2_vpc_subnet_facts:
    region: "{{region}}"
    filters:
      vpc-id: "{{stack.stack_outputs.VPCId}}"
      "tag:Name": "private-C"
  register: privatec_facts

- name: update privatec id to "{{privatec_facts.subnets.0.id}}"
  replace:
     dest: "/{{group_vars_path}}all/main.yml"
     regexp: "^privatec_subnet_id_{{region_name}}:.*$"
     replace: "privatec_subnet_id_{{region_name}}: {{privatec_facts.subnets.0.id}}"
